### ISSUE TITLE
Realtime chart range selection problem

### ISSUE THREAD

**Issue by cihadturhan** [HumbleSoftware/envisionjs#25]
Hi,
First of all, awesome tool. I've tried Highcharts and D3 but they have performance problems as they are svg library. So this is perfect alternative.

The problem is I can't select a range when the chart is realtime. I've recorded a 15 secs video and linked below. 
_Note: (Red circles represents mousedown event)_

[video link](http://www.mediafire.com/download/dx1jw078avdkic3/bugreport.wmv)

Edit: 
[youtube link](http://www.youtube.com/watch?v=SHM_UcPaGfM)

**Comment by Zielak** [comment]
Why didn't you post it somewhere with proper video player. I get shivers when I'm about to download files from hosting sites :)

Besides, I can't open the video on Mac...

**Comment by cihadturhan** [comment]
Edited :)

**Comment by Zielak** [comment]
You can't select a range in this example because it was programmed mainly for realtime updates. It spends 0.5s on moving range (for the smooth animation) and re-drawing chart (frame-by-frame) every second. You can of course change this functionality yourself to temporarily stop the automatic refresh whenever user presses mouse button and resume it on mouseup event, or whatever you fancy.

**Comment by cihadturhan** [comment]
Aha, I thought dragging is enabled on this chart too. Thanks, I'm closing then.

**Comment by cesutherland** [comment]
I may have some other ideas here too.  Can you create a fiddle of your implementation?  (This could get you started: http://jsfiddle.net/cesutherland/LurmY/).
